name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/mmx233/tdlib:alpine

#      - name: Login
#        run: docker login --username=${{ secrets.username }} --password=${{ secrets.pwd }} registry.cn-shanghai.aliyuncs.com
#
#      - name: Push
#        run: docker push registry.cn-shanghai.aliyuncs.com/mmx233/apicenter:latest